package main

import "fmt"

func findTheDifference(s string, t string) byte {
	temp1, temp2 := []byte(s), []byte(t)
	var sum1 , sum2 byte
	for _, element := range temp1 {
		sum1 += element
	}
	for _, element := range temp2 {
		sum2 += element
	}

	return sum2 - sum1
}
func findTheDifference1(s string, t string) byte {
	temp1, temp2 := []byte(s), []byte(t)
	var sum1 byte
	for i := 0; i < len(temp1); i++ {
		sum1 += temp2[i] - temp1[i]
	}

	return sum1 + temp2[len(temp2)-1]
}

func main() {
	fmt.Println(string(findTheDifference("abcd","abcde"))) // e
	fmt.Println(string(findTheDifference1("abcd","abcde"))) // e
}

// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
//
// Example:
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.